version: "2"
services:
  jupyterlab:
    build:
      context: .
    user: root
    ports:
      - "80:8888"
    volumes:
      - "./work:/home/jovyan/work"
    environment:
      NB_UID: 8888
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab
